[BD-14] Handle field-based errors for XBlock addition properly.
edx/frontend-app-library-authoring pull request #11
Opened 2020-09-15 17:46 UTC by Kelketek

This PR updates the XBlock submission buttons to use Paragon components and to handle error messages more properly. While we are still waiting on a future task to improve the UX for block creation and editing, we found that this components broken functionality (as well as its lack of use of accessible elements) was confusing to new developers and also left an example of what **not** to do in the code, which might be mistakenly copied.

This cleans up the error handling, making the transition to a new interface cleaner, and making sure that anyone testing using this repo can get proper feedback in case they do something like put a space in a block's description ID. It also factors out error normalizing code into its own function, which can be used elsewhere.

**Merge deadline**: None-- honestly this could stand to wait a little while because merging it will require a rebase in other places. I'd rather rebase this one later than those ones.

** Screenshots
![Screen Shot 2020-09-15 at 12 27 19 PM](https://user-images.githubusercontent.com/1099483/93245571-1d0ca100-f751-11ea-80b9-f46dc8a0ee4a.png)
![Screen Shot 2020-09-15 at 12 29 46 PM](https://user-images.githubusercontent.com/1099483/93245580-20a02800-f751-11ea-891e-287b418e44b9.png)

**Testing instructions**:

1. Submit a new block with a space in the name. Verify a useful error is generated.
2. Submit a new block with each of the following changes to studio in place. In each case, the frontend should do something useful.
    1. Force the Studio to throw Http404.
    2. Force the Studio to throw ValidationError('This is a test.')
    3. Force the studio to raise an uncaught exception, like RuntimeError.
    4. Shut down the studio.

**Author notes and concerns**:

1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
   Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_FEATURES:
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
```

2020-09-15 17:46 UTC, edx-webhook commented
Thanks for the pull request, @Kelketek! I've created [BLENDED-589](https://openedx.atlassian.net/browse/BLENDED-589) to keep track of it in Jira.   More details are on the [BD-14](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) project page.

When this pull request is ready, tag your edX technical lead.

<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->

2020-09-16 14:12 UTC, kdmccormick commented
Thanks for the PR @Kelketek 
> Merge deadline: None-- honestly this could stand to wait a little while because merging it will require a rebase in other places. I'd rather rebase this one later than those ones.

Sounds good. Marking this as Blocked to signal that I'll be focusing on the earlier PRs for now.

2020-09-21 19:32 UTC, arbrandes requested changes
Thanks @Kelketek, this is a great improvement and I'm all for it.  In testing, it works well.  As you put it above, though, it'll require some rebasing before merging.

2020-09-21 20:12 UTC, Kelketek commented on src/library-authoring/common/helpers.js
> +  /* Normalize error data. This should probably be made into its own function later, since these cases could */
Cleared. The docstring above this function handles what I was going to say, and in the middle of writing this comment about how 'this should probably be made its own function later', I decided to do it now instead.

2020-09-22 12:31 UTC, arbrandes commented on src/library-authoring/common/helpers.js
> +  /* Normalize error data. This should probably be made into its own function later, since these cases could */
@Kelketek, I figured something like this was the case.  Thanks for explaining. :)

2020-10-02 19:39 UTC, kdmccormick approved these changes
Fine by me. Leaning on @arbrandes 's review here; I haven't tested this myself.

2020-10-06 15:04 UTC, merged